version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - notifications_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - notifications_network
    volumes:
      - mysql_data:/var/lib/mysql

  notification_sender:
    build: ./notification_sender
    container_name: notification_sender
    ports:
      - "8000:8000"  # Expose FastAPI endpoint
    depends_on:
      - rabbitmq
      - mysql_db
    networks:
      - notifications_network

    working_dir: /app

  notification_receiver:
    build: ./notification_receiver
    container_name: notification_receiver
    depends_on:
      - rabbitmq
      - mysql_db
    networks:
      - notifications_network

  sender_tests:
    build: ./notification_sender
    container_name: notification_sender_tests
    depends_on:
      - rabbitmq
    networks:
      - notifications_network
    command: [ "pytest", "tests/" ]
    working_dir: /app
    profiles:
      - test

  receiver_tests:
    build:
      context: ./notification_receiver
    container_name: notification_receiver_tests
    depends_on:
      - mysql_db
      - rabbitmq
    networks:
      - notifications_network
    command: [ "pytest", "tests/" ]
    working_dir: /app
    profiles:
      - test

networks:
  notifications_network:
    driver: bridge

volumes:
  mysql_data:
